name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Create Windows-CRD folder

      run: New-Item -ItemType Directory -Path $env:USERPROFILE\Desktop\Windows-CRD

    - name: Download playit.exe

      run: Invoke-WebRequest -Uri 'https://playit.gg/downloads/playit-0.8.1-beta-signed.exe' -OutFile $env:USERPROFILE\Desktop\Windows-CRD\playit.exe

    - name: Download DUCSetup.exe

      run: Invoke-WebRequest -Uri 'https://www.noip.com/client/DUCSetup_v4_1_1.exe' -OutFile $env:USERPROFILE\Desktop\Windows-CRD\DUCSetup.exe
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
